# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: pygments
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: DMPED Ward Analysis Tool
subtitle: 'Deputy Mayor for Planning & Economic Development | Muriel Bowser, Mayor'

# Author/Organization info to be displayed in the templates
author:
  name: Office of the Deputy Mayor for Planning and Economic Development
  url: http://dmped.dc.gov

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/econintel-wardtool'

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: '/assets/img/we-are-wdc.png'
logoalt: We Are Washington DC

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: ./
- text: Map
  internal: true
  url: map.html
- text: Ward 1
  internal: true
  url: ward-1.html
- text: Ward 2
  internal: true
  url: ward-2.html
- text: Ward 3
  internal: true
  url: ward-3.html
- text: Ward 4
  internal: true
  url: ward-4.html
- text: Ward 5
  internal: true
  url: ward-5.html
- text: Ward 6
  internal: true
  url: ward-6.html
- text: Ward 7
  internal: true
  url: ward-7.html
- text: Ward 8
  internal: true
  url: ward-8.html  

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: econintel-wardtool
  description:
  url: https://github.com/DCgov/econintel-wardtool

# google_analytics_ua: TBA

# Style Variables
brand_color: "#BF0000"
